# k8s/postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d/ # Куда мы ее подключаем

      # --- И ВОТ ВТОРАЯ ЧАСТЬ ИЗМЕНЕНИЯ ---
      volumes:
        - name: postgres-init-scripts # Создаем "виртуальную флешку"
          configMap:
            name: postgres-init-config # И говорим, что ее содержимое - это наш ConfigMap